name: proxy_stack

networks:
  proxy_net:
    name: proxy_net
    driver: bridge

volumes:
  nginx_proxy_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/violet/docker-volumes/nginx_proxy_data

  nginx_proxy_letsencrypt:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/violet/docker-volumes/nginx_proxy_letsencrypt

services:
  nginx_proxy_manager:
    container_name: nginx_proxy_manager
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    networks:
      - proxy_net
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - nginx_proxy_data:/data
      - nginx_proxy_letsencrypt:/etc/letsencrypt
